# kubectl apply -f pod3-jupyter.yaml 
# kubectl port-forward student4-jupyter 8888:8888 
apiVersion: v1
kind: Pod
metadata:
  name: <student-user-name>-jupyter
  labels:
    app: jupyter-lab
spec:
  containers:
  - name: jupyter-lab-container
    image: jupyter/datascience-notebook:latest
    ports:
    - containerPort: 8888
    command: ["start-notebook.sh"]
    args: ["--NotebookApp.token=''", "--NotebookApp.password=''"]
    volumeMounts:
    - name: notebook-volume
      mountPath: /home/jovyan/work
  volumes:
  - name: notebook-volume
    emptyDir: {}
