docs_dir: docs/
repo_name: 'CyVerse-learning-materials/container-camp'
repo_url: 'https://github.com/CyVerse-learning-materials/container-camp'

site_name: 'Container Camp Spring 2022'
site_description: 'Documentation for CyVerse Platforms and Education'
site_author: 'CyVerse Science Team'
site_url: 'https://learning.cyverse.org/container-camp/'

edit_uri: edit/mkdocs/docs

# Copyright
copyright: 'Copyright &copy; 2022 CyVerse'

# Navigation Page

nav:
  - 'Home': 
    - index.md 
  - 'Getting Started': 
    - 'Code of Conduct': getting_started/code_conduct.md
    - 'Logistics': getting_started/logistics.md
    - 'Schedule': getting_started/schedule.md
    - 'Setup': getting_started/setup.md
  - 'Docker':
    - 'Introduction to Docker': docker/intro.md
    - 'Finding the right container': docker/registry.md
    - 'Building Docker Containers': docker/build.md
    - 'Advanced use of Docker': docker/advanced.md
    - 'GitHub Actions and Docker': docker/actions.md
    - 'Running multi-container Applications': docker/compose.md 
  - 'Singularity':
    - 'Introduction to Singularity': singularity/intro.md
    - 'Advanced use of Singularity': singularity/advanced.md
    - 'Using Singularity on HPC/HTC': singularity/hpc.md
  - 'Orchestration':
    - 'Kubernetes': orchestration/k8s.md
    - 'CyVerse CACAO': orchestration/cacao.md
    - 'Manage a private registry': orchestration/registry.md
  - 'Cloud Services':
    - 'Jetstream-2': cloud/js2.md
    - 'GitHub CodeSpaces': cloud/codespaces.md
  - 'Useful Resources':
    - 'Docker': resources/docker.md
    - 'Singularity': resources/singularity.md
    - 'Kubernetes': resources/k8s.md

# JavaScript for Intercom Widget
extra_javascript:
  - javascripts/intercom-learning.js
  
# Set theme to `readthedocs`
# must also set Action to use `@nomaterial` branch instead of `@master` for material
theme:
  name: material
# setting features for the navigation tab
  features:
    - navigation.instant
      #- navigation.expand
    - navigation.tracking
      #- navigation.sections
    - navigation.indexes
    - toc.follow
  # Default values, taken from mkdocs_theme.yml
  language: en
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Regular
  favicon: assets/favicon.png
  icon:
    logo: octicons/container-24 

# Options
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/
    - icon: fontawesome/brands/github
      link: https://github.com/cyverse-learning-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyverseorg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cyverse.org
    - icon: fontawesome/brands/docker
      link: https://harbor.cyverse.org/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/CyverseOrgProject
  analytics:
    provider: google
    property: UA-72224033-6

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
